Restrict external ips
cncf/cnf-testsuite pull request #1186
Opened 2022-01-31 22:06 UTC by nsagark

## Description
Adding test to integrate kyverno to CNF testsuite. The test checks if there are any external IP's in the service configuration and reports accordingly

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [x] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [x] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2022-02-03 15:30 UTC, nsagark commented
Planning to still write the spec tests for this test.

2022-02-09 12:04 UTC, HashNuke requested changes
The test itself LGTM.

I've added some notes about organizing some pieces of code.

2022-02-09 12:04 UTC, HashNuke commented on src/tasks/workload/security.cr
> +  result = KubectlClient::Get.policy_report_allnamespaces()
If the "Policy Report" resource is a custom require defined by Kyverno, then it would be better if these helpers are moved to the Kyverno module/class. This way we know the pieces of code that is related to the Kyverno integration - makes maintenance easier.

2022-02-09 12:04 UTC, HashNuke commented on utils/kubectl_client/kubectl_client.cr
> +    def self.cluster_policy_report()
As mentioned in another comment, moving this helper to the Kyverno module would be better since PolicyReport is a custom resource defined by Kyverno. Same for other helpers that are related to policy report in the KubectlClient module.

2022-02-17 21:28 UTC, merged