updated code and documentation for disallow_helm_tiller test using kyverno
cncf/cnf-testsuite pull request #1187
Opened 2022-01-31 22:11 UTC by nsagark

## Description
Adding test to integrate kyverno to CNF testsuite. The test checks if there are any containers that use tiller/helm v2 images and reports accordingly

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [x] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [x] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2022-02-03 15:32 UTC, nsagark commented
Planning to write spec tests for this test

2022-02-09 12:25 UTC, HashNuke requested changes
Added some notes about using helper methods to wait for resources to be ready/available.


The comments on #1186 about the following applies to this PR too:
* Cloning the policies repo into tools dir instead of using a manifest url in each test.
* Moving helpers PolicyReport helpers away from KubectlClient into a Kyverno specific module.

2022-02-09 12:25 UTC, HashNuke commented on USAGE.md
> +<b>Tiller Images Details:</b> Tiller, found in Helm v2, has known security challenges. It requires administrative privileges and acts as a shared resource accessible to any authenticated user. Tiller
Would be good to link to any documentation that mentions issues with Tiller here (like the security challenges). External sources help validate the details mentioned and provide additional details.

2022-02-09 12:25 UTC, HashNuke commented on src/tasks/workload/security.cr
> +  sleep(3.seconds)
If the intention of using `sleep` here is to wait for resources to be ready, then we should instead use one of the available helpers. Below is some info to help out:

* `KubectlClient::Get.resource_wait_for_install` can be used to wait for resources to be ready. Since the manifest installs `ClusterPolicy`, which is a custom resource defined by Kyverno, the `resource_wait_for_install` helper might have to be extended to support custom resources (not ClusterPolicy specifically).
* There are also various places in the code where a loop is being used to check for resource readiness (grepping for pod_status might help identify these pieces of code)
* If these wait times are across all kyverno tests, then it might even help add a custom wait helper to the Kyverno module.

2022-02-17 20:27 UTC, merged