Refactor USAGE.md #1371 #1372
cncf/cnf-testsuite pull request #1496
Opened 2022-06-10 22:24 UTC by denverwilliams

## Description
Refactor and remove any duplicate documentation from USAGE.md

## Issues:
Refs: #1371 #1372

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2022-06-11 20:33 UTC, agentpoyo requested changes
LGTM except grammar and spelling mistakes pointed out that need attention.

2022-06-11 20:33 UTC, agentpoyo commented on RATIONALE.md
> +> If the memory policies for a CNF are not set and fine grained enough, containers on the node can be killed based on their oom_score and the QoS class a given pod belongs to (bestEffort ones are fir
```suggestion
> If the memory policies for a CNF are not set and granular, containers on the node can be killed based on their oom_score and the QoS class a given pod belongs to (best-effort ones are first to be targeted). This eval is extended to all pods running on the node, thereby causing a bigger blast radius. 
```

2022-06-11 20:33 UTC, agentpoyo commented on RATIONALE.md
> +> OpenMetrics is the de-facto standard for transmitting cloud-native metrics at scale, with support for both text representation and Protocol Buffers and brings it into an Internet Engineering Task F
```suggestion
> OpenMetrics is the de facto standard for transmitting cloud native metrics at scale, with support for both text representation and Protocol Buffers and brings it into an Internet Engineering Task Force (IETF) standard. A CNF should expose metrics that are [OpenMetrics compatible](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md)
```

2022-06-11 20:33 UTC, agentpoyo commented on RATIONALE.md
> +> Mutable container filesystem can be abused to gain malicious code and data injection into containers. By default, containers are permitted mostly unrestricted execution within their own context. An
```suggestion
> Mutable container filesystem can be abused to gain malicious code and data injection into containers. By default, containers are permitted unrestricted execution within their own context. An attacker who has access to a container, [can create files](https://hub.armo.cloud/docs/c-0017) and download scripts as they wish, and modify the underlying application running on the container.
```

2022-06-11 20:33 UTC, agentpoyo commented on RATIONALE.md
> +> Defining and using labels help to identify semantic attributes of your application or Deployment. A common set of labels allows tools to work collaboratively, describing objects in a common manner
```suggestion
> Defining and using labels help identify semantic attributes of your application or Deployment. A common set of labels allows tools to work collaboratively, while describing objects in a common manner that all tools can understand. You should use recommended labels to describe applications in a way that can be queried.
```

2022-06-11 20:33 UTC, agentpoyo commented on RATIONALE.md
> +> * If Kubernetes dashboard is exposed externally in Dashboard versions before 2.01, it will allow unauthenticated remote management of the cluster. It's best practive not expose the K8s Dashboard, o
```suggestion
> * If Kubernetes dashboard is exposed externally in Dashboard versions before 2.01, it will allow unauthenticated remote management of the cluster. It's best practice to not expose the K8s Dashboard or any management planes if they're unsecured.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Make sure that your CNFs containers are not shareing the same [database](https://martinfowler.com/bliki/IntegrationDatabase.html).
```suggestion
Make sure that your CNF containers are not sharing the same [database](https://martinfowler.com/bliki/IntegrationDatabase.html).
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +A mitigation stagagy(in this case keep the timeout i.e., access latency low) could be via some middleware that can switch traffic based on some SLOs parameters.
```suggestion
A mitigation strategy (in this case keep the timeout i.e., access latency low) could be some middleware that can switch traffic based on some SLOs parameters.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Ensure that your CNF is resilient to heavy memory usage and can maintain some level of avaliabliy.
```suggestion
Ensure that your CNF is resilient to heavy memory usage and can maintain some level of availability. 
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Ensure that your CNF is resilient to continuous and heavy disk IO load and can maintain some level of avaliabliy
```suggestion
Ensure that your CNF is resilient to continuous and heavy disk IO load while maintaining some level of availability
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Ensure that your CNF is resilient to a lossy/flaky network and can maintain a level of avaliabliy.
```suggestion
Ensure that your CNF is resilient to a lossless/flaky network and can maintain a level of availability.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Ensure that your CNF is resilient to erroneously duplicated packets and can maintain a level of avaliabliy.
```suggestion
Ensure that your CNF is resilient to erroneously duplicated packets and can maintain a level of availability.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Ensure that your CNF is both using & publishing traces to Jaeger.
```suggestion
Ensure that your CNF is using & publishing traces to Jaeger.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Make sure to not define external IPs in your kubernetes service configuration
```suggestion
Make sure to not define external IPs in your kubernetes service configuration.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Remove privileged capabilities by setting the securityContext.privileged to false. If you must deploy a Pod as privileged, add other restriction to it, such as network policy, Seccomp etc and still r
```suggestion
Remove privileged capabilities by setting the securityContext.privileged to false. If you must deploy a Pod as privileged, add other restrictions to it, such as network policy, Seccomp, etc, and still remove all unnecessary capabilities.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +If your application does not need root privileges, make sure to define the runAsUser and runAsGroup under the PodSecurityContext to use user ID 1000 or higher, do not turn on allowPrivlegeEscalation
```suggestion
If your application does not need root privileges, make sure to define the runAsUser and runAsGroup under the PodSecurityContext to use user ID 1000 or higher. Do not turn on allowPrivlegeEscalation bit and runAsNonRoot as true.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Apply least privilege principle and remove hostPID and hostIPC from the yaml file(s) privileges unless they are absolutely necessary.
```suggestion
Apply least privilege principle and remove hostPID and hostIPC from the yaml configuration privileges unless they are absolutely necessary.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +When specifying container images, always specify a tag and ensure to use an immutable tag that maps to a specific version of an application Pod. Remove any usage of the `latest` tag, as it is not gua
```suggestion
When specifying container images, always specify a tag and ensure to use an immutable tag that maps to a specific version of an application Pod. Remove any usage of the `latest` tag, as it is not guaranteed to always point to the same version of the image.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +## [Versioned tag](docs/LIST_OF_TESTS.md#versioned-tag)
Wasn't one of these "tag" tests removed?

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Ensure that your CNF is resilient to DNS/resolution failures can maintain a level of avaliabliy.
```suggestion
Ensure that your CNF is resilient to DNS resolution failures can maintain a level of availability.
```

2022-06-11 20:33 UTC, agentpoyo commented on USAGE.md
> +Reboot the Worker nodes for your Kubernetes cluster virify that all node survive a reboot and can successfully reschedule workloads.
```suggestion
Reboot the Worker nodes for your Kubernetes cluster and it will verify that all nodes survive a reboot and can successfully reschedule workloads. 
```

2022-06-13 20:15 UTC, denverwilliams commented on USAGE.md
> +## [Versioned tag](docs/LIST_OF_TESTS.md#versioned-tag)
Yes, it was removed from the Cert command. But it's still a test under the configuration category and hasn't been removed from the test suite.

2022-06-13 20:31 UTC, agentpoyo approved these changes
LGTM

2022-06-13 20:31 UTC, merged