Fixed links🔗
cncf/cnf-testsuite pull request #742
Opened 2021-04-27 16:44 UTC by himanshu007-creator

## Description
This Pull Request solves the links issues. All references of <code>https://github.com/cncf/cnf-conformance</code> are replaced to <code>https://github.com/cncf/cnf-conformance</code>
In a file [USAGE.md], all references are changed to relative links

## Issues:
Refs: #724 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [x] Tasks in issue are checked off

2021-04-27 17:34 UTC, taylor requested changes
@himanshu007-creator please update the links which were changed in this PR to be relative links.  I've shown a few suggested, there are many more though in this PR.

2021-04-27 17:34 UTC, taylor commented on .github/ISSUE_TEMPLATE/bug-report.md
> +Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/master/USAGE.md) for more info about invoking commands and loggin
Please use a relative path.

2021-04-27 17:34 UTC, taylor commented on .github/ISSUE_TEMPLATE/new-example-cnf.md
> +- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/#installation) if needed
```suggestion
- [ ] Update [installation instructions](INSTALL.md) if needed
```

2021-04-27 17:34 UTC, taylor commented on .github/ISSUE_TEMPLATE/new-platform-test.md
> +- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/#installation) if needed
```suggestion
- [ ] Update [installation instructions](INSTALL.md) if needed
```

2021-04-27 17:34 UTC, taylor commented on .github/ISSUE_TEMPLATE/new-workload-test.md
> +- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/#installation) if needed
```suggestion
- [ ] Update [installation instructions](INSTALL.md) if needed
```

2021-04-27 17:34 UTC, taylor commented on CONTRIBUTING.md
> +- [Issues](https://github.com/cncf/cnf-testsuite/issues)
```suggestion
- [Issues](issues)
```

2021-04-27 17:34 UTC, taylor commented on CONTRIBUTING.md
> +Before starting work on a major feature, please reach out to us via [GitHub Issues](https://github.com/cncf/cnf-testsuite/issues) or Slack. We will make sure no one else is already working on it and
```suggestion
Before starting work on a major feature, please reach out to us via [GitHub Issues](issues) or Slack. We will make sure no one else is already working on it and ask you to open a [GitHub issue](issues/new/choose).
```

2021-04-27 17:34 UTC, taylor commented on CONTRIBUTING.md
> +  - [Good first issues](https://github.com/cncf/cnf-testsuite/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
```suggestion
  - [Good first issues](issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
```

2021-04-27 18:00 UTC, agentpoyo commented on tools/ephemeral_env/README.md
> +Prereqs: https://github.com/cncf/cnf-testsuite/blob/master/KIND-INSTALL.md
```suggestion
Prereqs: https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md
```

2021-04-27 18:24 UTC, agentpoyo commented
> @himanshu007-creator please update the links which were changed in this PR to be relative links. I've shown a few suggested, there are many more though in this PR.

The relative paths won't work in the issue templates, need the full path URL since the issues don't sit in the same root directory. I don't see the templates changing again unless we change the default branch and or the doc they're linking to changes (name or header link).

2021-04-29 05:33 UTC, himanshu007-creator commented on .github/ISSUE_TEMPLATE/bug-report.md
> +Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/master/USAGE.md) for more info about invoking commands and loggin
wont work in ISSUE TEMPLATE 
reference:-https://github.com/cncf/cnf-testsuite/pull/742#issuecomment-827820452

2021-04-29 05:33 UTC, himanshu007-creator commented on .github/ISSUE_TEMPLATE/new-example-cnf.md
> +- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/#installation) if needed
wont work in ISSUE TEMPLATE 
reference:-https://github.com/cncf/cnf-testsuite/pull/742#issuecomment-827820452

2021-04-29 05:34 UTC, himanshu007-creator commented on CONTRIBUTING.md
> +- [Issues](https://github.com/cncf/cnf-testsuite/issues)
done

2021-04-29 05:36 UTC, himanshu007-creator commented on CONTRIBUTING.md
> +Before starting work on a major feature, please reach out to us via [GitHub Issues](https://github.com/cncf/cnf-testsuite/issues) or Slack. We will make sure no one else is already working on it and
done

2021-04-29 05:38 UTC, himanshu007-creator commented on .github/ISSUE_TEMPLATE/bug-report.md
> +Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/master/USAGE.md) for more info about invoking commands and loggin
done

2021-04-29 05:39 UTC, himanshu007-creator commented on .github/ISSUE_TEMPLATE/new-example-cnf.md
> +- [ ] Update [Test Categories md](TEST-CATEGORIES.md) if needed
done

2021-04-29 05:44 UTC, himanshu007-creator commented on .github/ISSUE_TEMPLATE/new-example-cnf.md
> +- [ ] Update [Pseudo Code md](PSEUDO-CODE.md) if needed
done

2021-04-29 05:44 UTC, himanshu007-creator commented on .github/ISSUE_TEMPLATE/new-example-cnf.md
> +- [ ] Update [USAGE md](USAGE.md) if needed
done

2021-04-29 18:31 UTC, agentpoyo approved these changes
LGTM

2021-04-29 21:10 UTC, merged