Create CONTRIBUTION_LADDER.md
cncf/cnf-testsuite pull request #791
Opened 2021-05-26 21:57 UTC by taylor

https://github.com/cncf/cnf-testsuite/discussions/790

## Description
(name of issue/change)

## Issues:
Refs: #NNN

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2021-05-27 18:48 UTC, agentpoyo approved these changes
LGTM  (This was by accident, I thought I was in another PR) My suggestions added below.

2021-05-27 20:01 UTC, lixuna requested changes

2021-05-27 20:01 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Create new mixin repositories
```suggestion
```

2021-05-27 20:01 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +TBD
```suggestion
```

2021-05-27 22:17 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +* Share a bundle that you made and how it went.
No clue. Let's delete it.

2021-05-28 14:47 UTC, lixuna requested changes

2021-05-28 14:47 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Share a bundle that you made and how it went.
```suggestion
```

2021-05-28 15:23 UTC, agentpoyo requested changes

2021-05-28 15:23 UTC, agentpoyo commented on CONTRIBUTION_LADDER.md
> +You must follow our [Code of Conduct](code-of-conduct.md).
Is there a better way to say "You must..."? Maybe something like "It is fundamental to follow our [Code of Conduct](code-of-conduct.md) as a contributor".

2021-05-28 15:23 UTC, agentpoyo commented on CONTRIBUTION_LADDER.md
> +who may make good contributors. But don’t be shy, if you feel that this is you,
```suggestion
who make good contributors. But don’t be shy, if you feel that this is you,
```

2021-05-28 16:47 UTC, taylor reviewed
@agentpoyo I made a few changes based on your comments. I am not sure about the 2 suggestions for changing must to will.  Look at my latest suggestion for the community member must follow the code of conduct.  It seems like that and the others would be good as must to me.

cc: @lixuna @williscool

2021-05-28 16:47 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +  * [How to become a contributor](#how-to-become-a-contributor)
@agentpoyo suggest edit please :)

2021-05-28 16:47 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +You must follow our [Code of Conduct](code-of-conduct.md).
```suggestion
Community members must follow our [Code of Conduct](code-of-conduct.md).
```

How about this @agentpoyo

2021-05-28 17:13 UTC, agentpoyo commented on CONTRIBUTION_LADDER.md
> +Contributors must agree to and follow this Contributing Guide.
How about:  "We ask contributors to agree and follow this Contributing Guide" @taylor

2021-05-28 17:15 UTC, agentpoyo commented on CONTRIBUTION_LADDER.md
> +You must follow our [Code of Conduct](code-of-conduct.md).
That does sound better. The word "must" just seems very authoritarian to me.

2021-05-28 17:36 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +Contributors must agree to and follow this Contributing Guide.
@agentpoyo sounds good. Add a suggest edit please

2021-05-28 17:37 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +Maintainers must agree to and follow the [Reviewing Guide](REVIEWING.md).
@agentpoyo add a suggest edit please similar to your contributor suggestion above https://github.com/cncf/cnf-testsuite/pull/791#discussion_r641698992

2021-06-02 21:01 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +Contributors must agree to and follow this Contributing Guide.
new wording just says follow ...

2021-06-02 21:01 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +Maintainers must agree to and follow the [Reviewing Guide](REVIEWING.md).
new wording just says follow ...

2021-08-12 15:11 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +* Be a [Code Owner](.github/CODEOWNERS) and have reviews automatically requested.
Added .github/CODEOWNERS to this PR. This makes a PR request automatically add those people as reviewers.  See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners

2021-08-12 15:26 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +* Be a [Code Owner](.github/CODEOWNERS) and have reviews automatically requested.
@lixuna 👆🏻

2021-08-12 15:52 UTC, agentpoyo requested changes
LGTM but did have a few suggestions or thoughts added.

2021-08-12 18:11 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +* Come chat with us in [Slack](https://cloud-native.slack.com/archives/C014TNCEX8R).
Add a suggest edit @agentpoyo

2021-08-16 14:31 UTC, agentpoyo commented on CONTRIBUTION_LADDER.md
> +* Come chat with us in [Slack](https://cloud-native.slack.com/archives/C014TNCEX8R).
```suggestion
* Come chat with us in [Slack](https://cloud-native.slack.com/archives/C014TNCEX8R) or start a [discussion](https://github.com/cncf/cnf-testsuite/discussions).
```

2021-08-16 14:32 UTC, agentpoyo commented on CONTRIBUTION_LADDER.md
> +Contributors must agree to and follow this Contributing Guide.
```suggestion
We ask that contributors agree to and follow this Contributing Guide.
```

2021-08-16 14:34 UTC, agentpoyo requested changes
I made a few suggested changes. @taylor @lixuna

2021-08-16 20:35 UTC, lixuna requested changes

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Request a live demonstration and introduction of the test suite
```suggestion
* Request a live demonstration and introduction of the test suite ([book a time on Calendly](https://calendly.com/cnftestsuite))
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Read the [install guide](INSTALL.md), [usage guide](USAGE.md), [FAQ](FAQ.md), and other documentation.
```suggestion
* Read the [install guide](INSTALL.md), [usage guide](USAGE.md), [FAQ](FAQ.md), and other documentation
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Come chat with us in [Slack](https://cloud-native.slack.com/archives/C014TNCEX8R) or start a [discussion](https://github.com/cncf/cnf-testsuite/discussions).
```suggestion
* Come chat with us in [Slack](https://cloud-native.slack.com/archives/C014TNCEX8R) or start a [discussion](https://github.com/cncf/cnf-testsuite/discussions)
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +Contributors will agree to and follow this Contributing Guide.
```suggestion
Contributors will agree to and follow this [Contributing Guide](CONTRIBUTING.md).
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Comment on issues with your experiences and opinions.
```suggestion
* Comment on issues with your experiences and opinions
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Add your comments and reviews on pull requests.
```suggestion
* Add your comments and reviews on pull requests
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Contribute pull requests.
```suggestion
* Contribute pull requests
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Open issues with bugs, enhancement ideas, and questions.
```suggestion
* Open issues with bugs, enhancement ideas, and questions
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Review pull requests.
```suggestion
* Review pull requests
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Be a [Code Owner](.github/CODEOWNERS) and have reviews automatically requested.
```suggestion
* Be a [Code Owner](.github/CODEOWNERS) and have reviews automatically requested
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Merge pull requests.
```suggestion
* Merge pull requests
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Help foster a safe and welcoming environment for all project participants.
```suggestion
* Help foster a safe and welcoming environment for all project participants
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +  This will include understanding and enforcing our [Code of Conduct](code-of-conduct.md).
```suggestion
  This will include understanding and enforcing our [Code of Conduct](code-of-conduct.md)
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +  contributors, and other maintainers to review.
```suggestion
  contributors, and other maintainers to review
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +* Triage issues, e.g. adding labels, promoting discussions, finalizing decisions.
```suggestion
* Triage issues, e.g. adding labels, promoting discussions, finalizing decisions
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +  execute agenda.
```suggestion
  execute agenda
```

2021-08-16 20:35 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +We ask that Maintainers agree to and follow the [Reviewing Guide](REVIEWING.md).
delete: we don't have a reviewing guide yet

2021-08-16 21:37 UTC, lixuna requested changes

2021-08-16 21:37 UTC, lixuna commented on CONTRIBUTION_LADDER.md
> +reach out to one or more of the admins.
```suggestion
reach out to one or more of the admins.


## Emeritus Maintainers
Former maintainers are recognized with an honorary Emeritus Maintainer status, and have their names permanently listed in the [maintainer file](MAINTAINERS.md) as a form of gratitude for their contributions.
```

2021-08-16 22:39 UTC, taylor commented on CONTRIBUTION_LADDER.md
> +We ask that Maintainers agree to and follow the [Reviewing Guide](REVIEWING.md).
```suggestion
```

deleting at @lixuna suggestion

2021-08-16 22:52 UTC, williscool commented on .github/CODEOWNERS
> +/tools/ @denverwilliams @wavell @hashnuke @agentpoyo
I think it would be better to a named group as the owner (i.e. cnf-testsuite-infra) and have that be the owner of the code so that way is easier to add and remove people

2021-08-16 22:52 UTC, williscool commented on .github/CODEOWNERS
> +/tools/ @denverwilliams @wavell @hashnuke @agentpoyo
lgtm but think this would be better

2021-08-16 23:29 UTC, taylor commented on .github/CODEOWNERS
> +/tools/ @denverwilliams @wavell @hashnuke @agentpoyo
@williscool agreed. the problem with github groups is they are org level. When/if the testsuite is under it's own org this will be possible. until then it's problematic to do it in a large org like cncf

2021-08-17 00:01 UTC, williscool commented on .github/CODEOWNERS
> +/tools/ @denverwilliams @wavell @hashnuke @agentpoyo
ah!

2021-08-17 00:02 UTC, williscool approved these changes
lgtm

2021-08-17 00:14 UTC, agentpoyo approved these changes
Looks good to me!

2021-08-18 15:30 UTC, merged