doc updates to reference mac os x support for source installs #647
cncf/cnf-testsuite pull request #796
Opened 2021-05-31 22:00 UTC by agentpoyo

## Description
MacOS source install verification and proof of concept. 

## Issues:
Refs: #647 

## How has this been tested:
 - [ ] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2021-06-01 15:18 UTC, agentpoyo commented
@taylor #647 in Peer Review

2021-06-02 00:06 UTC, taylor approved these changes
@agentpoyo looks good. the one addition you could make is MacOS on Intel. I can not test Arm (yet)

2021-06-02 01:21 UTC, agentpoyo commented
> @agentpoyo looks good. the one addition you could make is MacOS on Intel. I can not test Arm (yet)

We actually don't mention ARM for Linux or WSL, should we amend to support those (I think we've tested but can't recall).

2021-06-02 13:36 UTC, agentpoyo commented
> @agentpoyo looks good. the one addition you could make is MacOS on Intel. I can not test Arm (yet)

@taylor We actually mention Intel (amd64) only supported for all platforms in the [FAQ](https://github.com/cncf/cnf-testsuite/blob/main/FAQ.md)

2021-06-03 22:54 UTC, taylor requested changes
2 updates for intel-only for macos

2021-06-03 22:54 UTC, taylor commented on FAQ.md
> +- The CNF Test Suite runs on most major Linux distributions, Mac OS X (source install only) and WSL (Windows Subsystem for Linux).
```suggestion
- The CNF Test Suite runs on most major Linux distributions, Mac OS X (Intel + source install only) and WSL (Windows Subsystem for Linux).
```

2021-06-03 22:54 UTC, taylor commented on SOURCE_INSTALL.md
> +We can assume you have access to a working kubernetes cluster. We recommend only running the cnf-testsuite on dev or test clusters. The source install steps have been verified on most Linux distribut
```suggestion
We can assume you have access to a working kubernetes cluster. We recommend only running the cnf-testsuite on dev or test clusters. The source install steps have been verified on most Linux distributions (Ubuntu, Debian and CentOS), Mac OS X (Intel only) and WSL as long as crystal-lang v0.35.1 is installed.
```

2021-06-03 23:07 UTC, agentpoyo commented on SOURCE_INSTALL.md
> +We can assume you have access to a working kubernetes cluster. We recommend only running the cnf-testsuite on dev or test clusters. The source install steps have been verified on most Linux distribut
Updated the location of the platforms to the TECH FAQ area before architecture support is mentioned.

2021-06-03 23:15 UTC, taylor approved these changes

2021-06-03 23:16 UTC, merged