Attempt "crystal tool format" on most files
cncf/cnf-testsuite pull request #854
Opened 2021-07-15 16:04 UTC by HashNuke

## Description
Except 5 files, most of the files have been formatted by "crystal tool format"

## Issues:
Refs: None

## How has this been tested:
 - [x] Covered by existing integration testing
 - [ ] Added integration testing to cover
 - [ ] Verified all A/C passes
     * [ ] develop
     * [ ] master
     * [ ] tag/other branch
 - [ ] Test environment
    * [ ] Shared Packet K8s cluster
    * [ ] New Packet K8s cluster
    * [ ] Kind cluster
 - [ ] Have not tested

## Types of changes:
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Documentation update

## Checklist:
**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. rescue block

**Issue**
- [ ] Tasks in issue are checked off

2021-07-15 16:19 UTC, taylor approved these changes
wow.  that is a lot @HashNuke.  
it may have been better to do this in a few PRs because its difficult to review so much at once... but i'm giving it a _lgtm_

2021-07-15 23:33 UTC, HashNuke commented
@taylor I agree. I’m relying on the test suite here for sanity checks.

If we are going to review this manually, I will do smaller PRs along with other issue PRs. It might take time to cover the codebase (over weeks/months) - but atleast the changeset will be reviewable.

Any thoughts?

2021-07-15 23:41 UTC, taylor commented
Of specs pass let's give it a try. Having it run as part of ci checks going forward should keep it from getting so far out of line.

2021-07-19 18:54 UTC, wavell commented on spec/utils/utils_spec.cr
> -        Process.run("grep -r -P '^(?!.+0\.0\.0\.0)(?![[:space:]]*0\.0\.0\.0)(?!#)(?![[:space:]]*#)(?!\/\/)(?![[:space:]]*\/\/)(?!\/\\*)(?![[:space:]]*\/\\*)(.+([0-9]{1,3}[\.]){3}[0-9]{1,3})'", shell:
@HashNuke This is definitely a problem :)

2021-07-19 20:20 UTC, taylor commented on spec/utils/utils_spec.cr
> +        Process.run("grep -r -P '^(?!.+0.0.0.0)(?![[:space:]]*0.0.0.0)(?!#)(?![[:space:]]*#)(?!//)(?![[:space:]]*//)(?!/\\*)(?![[:space:]]*/\\*)(.+([0-9]{1,3}[.]){3}[0-9]{1,3})'", shell: true) do |pr
```suggestion
        Process.run("grep -r -P '^(?!.+0.0.0.0)(?![[:space:]]*0.0.0.0)(?!#)(?![[:space:]]*#)(?!//)(?![[:space:]]*//)(?!/\\*)(?![[:space:]]*/\\*)(.+([0-9]{1,3}[.]){3}[0-9]{1,3})'", shell: true) do |proc|
```
```suggestion
        Process.run("grep -r -P '^(?!.+0\.0\.0\.0)(?![[:space:]]*0\.0\.0\.0)(?!#)(?![[:space:]]*#)(?!\/\/)(?![[:space:]]*\/\/)(?!\/\\*)(?![[:space:]]*\/\\*)(.+([0-9]{1,3}[\.]){3}[0-9]{1,3})'", shell: true) do |proc|
```

2021-07-19 20:39 UTC, taylor requested changes

2021-07-19 20:39 UTC, taylor commented on spec/utils/utils_spec.cr
> +        Process.run("grep -r -P '^(?!.+0.0.0.0)(?![[:space:]]*0.0.0.0)(?!#)(?![[:space:]]*#)(?!//)(?![[:space:]]*//)(?!/\\*)(?![[:space:]]*/\\*)(.+([0-9]{1,3}[.]){3}[0-9]{1,3})'", shell: true) do |pr
@wavell this puts it back the way it was before.

It is interesting that the format tool is changing a regex.  That is a bug in the tool IMO.

cc: @HashNuke

2021-07-19 20:39 UTC, taylor commented on spec/utils/utils_spec.cr
> +        Process.run("grep -r -P '^(?!.+0.0.0.0)(?![[:space:]]*0.0.0.0)(?!#)(?![[:space:]]*#)(?!//)(?![[:space:]]*//)(?!/\\*)(?![[:space:]]*/\\*)(.+([0-9]{1,3}[.]){3}[0-9]{1,3})'", shell: true) do |pr
@wavell @denverwilliams @HashNuke the content of a string inside of the function should not be touched IMO.  possibly a Crystal format tool error.  

The tool might not cause issues if this code was using the built-in Crystal regex instead of grep. It might be nicer in any case to refactor and maintain a Crystal version.  That could be a new issue.  

Maybe a "good first issue" since it should not require knowledge of the test suite specifically.

cc: @lixuna

2021-07-21 05:27 UTC, williscool requested changes
I would strongly prefer we did this in chunks.

Also @HashNuke can you comment on the diff between `crystal tool format` and ameba?

https://github.com/crystal-ameba/ameba

which you can run via

`crystal bin/ameba.cr`

2021-07-21 05:27 UTC, williscool requested changes
I would strongly prefer we did this in chunks.

Also @HashNuke can you comment on the diff between `crystal tool format` and ameba?

https://github.com/crystal-ameba/ameba

which you can run via

`crystal bin/ameba.cr`

2021-07-27 14:21 UTC, HashNuke commented
Closing this PR for now. Will review files one by one and them send separate PRs.

2021-07-27 14:21 UTC, closed without merging